version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5454:5432'
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password
    #   POSTGRES_DB: dev
    #   POSTGRES_USER: dev

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
